#!/usr/bin/env ruby

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'pullrequest'
require 'pullrequest/thor'

module Pullrequest
  class CLI < Thor
    include Pullrequest::Shell
    Aborted = Class.new(StandardError)

    desc "submit", "Submits Bitbucket pull request"
    def submit
      begin
        command
        if yes? "Print command?"
          $stdout.puts command
        end
        if yes? "Proceed?"
          execute command
        else
          raise Aborted
        end
      rescue Aborted
        if yes? "Review?"
          pullrequest.review
          retry
        end
      end
    end

    private

    def command
      pullrequest.command
    end

    def pullrequest
      @pullrequest ||= Bitbucket.new(self)
    end
  end
end

Pullrequest::CLI.start(ARGV.empty? ? ['submit'] : ARGV)
